version: '3'

services:
  getapp-site:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
    volumes:
      - ./boxes.yaml:/app/boxes.yaml
      - ./custom-boxes.yaml:/app/custom-boxes.yaml
      - ./.env:/app/.env
    restart: unless-stopped
